# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.mjs in odrinateur/git-sweep-pro — do not edit by hand.
class Gs < Formula
  desc "Safely prune local branches and sync with upstream"
  homepage "https://github.com/odrinateur/git-sweep-pro"
  version "0.4.0"
  license "GPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/odrinateur/git-sweep-pro/releases/download/v0.4.0/gs-darwin-arm64.tar.gz"
      sha256 "cba5e09a3a2cbbc55c73f8bc92f04cdad22f977507765e0393111674888d03ad"
    end
    on_intel do
      url "https://github.com/odrinateur/git-sweep-pro/releases/download/v0.4.0/gs-darwin-x64.tar.gz"
      sha256 "7b00113b5e0a955cd0c9014df1de44051eedecf7d07a1a586199dac6a6c3f3fa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/odrinateur/git-sweep-pro/releases/download/v0.4.0/gs-linux-arm64.tar.gz"
      sha256 "f066eec432c56270dbfd0268c3669e99fa675b7d34b7415e8d625bcf10fcb5c1"
    end
    on_intel do
      url "https://github.com/odrinateur/git-sweep-pro/releases/download/v0.4.0/gs-linux-x64.tar.gz"
      sha256 "cc06e6533d2d111c90a436b35129b0b096cd7114dfb867e3d1947c8191fa278b"
    end
  end

  def install
    bin.install "gs"
  end

  test do
    assert_match "0.4.0", shell_output("#{bin}/gs --version")
  end
end
